# deinlazy.toml

# Context filetype library for Vim script
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
on_ft = ['vim', 'html', 'toml']

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

# completing words in English
#[[plugins]]
#repo = 'ujihisa/neco-look'
#on_source = ['deoplete.nvim']

# lang

[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = 'vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = 'css'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'

[[plugins]]
repo = 'mattn/emmet-vim'
on_i = 1
hook_source = '''
source ~/.config/nvim/plugins/emmet-vim.rc.vim
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
hook_source = '''
source ~/.config/nvim/plugins/vim-vue.rc.vim
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform', 'tf', 'tfvars', 'tfstate']
hook_source = '''
source ~/.config/nvim/plugins/vim-terraform.rc.vim
'''

[[plugins]]
repo = 'juliosueiras/vim-terraform-completion'
on_ft = ['terraform', 'tf', 'tfvars', 'tfstate']
